name: Quini 6 Auto Sync

on:
  schedule:
    # Corre todos los jueves y lunes a las 03:00 UTC (00:00 ARG)
    - cron: '0 3 * * 1,4'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run Sync
        run: curl -I -s https://www.quini-6-resultados.com.ar/quini6/sorteos-anteriores.aspx
